### ISSUE TITLE
quantile.default becomes non-visible in R 3.1.0

### ISSUE THREAD

**Issue by appling** [USGS-R/smwrStats#1]
This is a problem for USGSwsStats / R / quantile.numeric.R, where quantile.default() is called directly rather than via UseMethod dispatch.

I discovered the problem when trying to call rloadest::predLoad() after updating R, but ultimately it seems to be coming from USGSwsStats::quantile.numeric. Here's an illustration of what happens under R 3.1.0:

```
  # Under R 3.1.0 [64 bit]
  summary(1:5)
  #   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  #   1       2       3       3       4       5 
  methods(quantile)
  #  [1] quantile.default* quantile.ecdf*    quantile.POSIXt* 
  library(USGSwsStats) #library(rloadest)
  # [Loading messages]
  summary(1:5)
  #   Error in quantile.numeric(object) : 
  #     could not find function "quantile.default"
  traceback()
  #   4: quantile.numeric(object)
  #   3: stats::quantile(object)
  #   2: summary.default(1:5)
  #   1: summary(1:5)
  methods(quantile)
  #  [1] quantile.default* quantile.ecdf*    quantile.numeric* quantile.POSIXt* 
```

The traceback() indicates that the quantile.numeric function, introduced by USGSwsStats, tries and fails to find quantile.default.

For comparison, the same code runs without error under R 3.0.3:

```
  # Under R 3.0.3 [64 bit]
  summary(1:5)
  #   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  #   1       2       3       3       4       5 
  methods(quantile)
  #  [1] quantile.default quantile.ecdf*   quantile.POSIXt*
  library(USGSwsStats) #library(rloadest)
  # [Loading messages]
  summary(1:5)
  #   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  #   1       2       3       3       4       5 
  methods(quantile)
  #  [1] quantile.default  quantile.ecdf*    quantile.numeric* quantile.POSIXt* 
```

Note that quantile.default was visible under R 3.0.3, but it is no longer visible under R 3.1.0.

I think the solution for this particular error is probably to use NextMethod() instead of quantile.default() within quantile.numeric(). I don't know whether other functions in the USGS packages are similarly affected by the changes in R 3.1.0, but it seems plausible; for example, several summary() methods have also changed in their visibility status in R 3.1.0.

**Comment by dlorenz-usgs** [comment]
It has been fixed. I've been out and my changes have shown up on the
 gitHub repository yet. This is the only one that I've discovered.
Dave

**Comment by appling** [comment]
Great, thanks! I'll look forward to the update.
