### ISSUE TITLE
Support multi-architecture?

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/smwrStats#3]
I depend (import) on `smwrQW` for `GSqwsr`.  `smwrQW` depends on `smwrStats`. `smwrStats` keeps giving me an error on CHECK of `GSqwsr`:

```
Error : package 'smwrStats' is not installed for 'arch = i386'
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
```

I was able to get around this by using `--no-multiarch` in the Check package arguments, but I'm not sure that is ideal.

My brain is hurting from trying to describe this.

**Comment by dlorenz-usgs** [comment]
That's weird. I was able to load the smwrStats library in 32bit mode. Try opening R in 32bit mode and loading smwrStats to verify that the package on the repository is OK.

**Comment by ldecicco-USGS** [comment]
`smwrStats` installed and loaded just fine in 32 and 64 bit. After specifically installing the 32 bit, I took the `--no-multiarch` out of the check command and it works.
