### ISSUE TITLE
smwrStats not working in R version 3.3

### ISSUE THREAD

**Issue by lsprague-USGS** [USGS-R/smwrStats#7]
Package will not load in R 3.3, which was released on May 3.  This issue is also affecting smwrQW, which has smwrStats as a dependency.

**Comment by ldecicco-USGS** [comment]
FYI, no package that have OS dependencies (need compiled code ie from Fortran) will be available on GRAN quite yet. I'll try to figure it out soon...but it's a rather non-trival task. Some of it has to do with setting up GRAN differently to handle the new set of folder requirements, and some might be package troubleshooting.

**Comment by ldecicco-USGS** [comment]
The Windows 3.3 binaries are up on GRAN. Mac's will get there eventually. But, if you want to try and have any issues, let me know here.

**Comment by ldecicco-USGS** [comment]
Reopen if this is still a problem
